# Generated by Django 5.2.12 on 2026-03-28 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('bloque_horario', models.CharField(choices=[('09:00', '09:00 - 10:00'), ('10:00', '10:00 - 11:00'), ('11:00', '11:00 - 12:00'), ('12:00', '12:00 - 13:00'), ('14:00', '14:00 - 15:00'), ('15:00', '15:00 - 16:00'), ('16:00', '16:00 - 17:00'), ('17:00', '17:00 - 18:00')], max_length=5)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('REALIZADA', 'Realizada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=10)),
                ('descripcion_falla', models.TextField(help_text='Breve descripción del problema del electrodoméstico')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.cliente')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.tecnico')),
            ],
        ),
    ]
