# Generated by Django 5.2.12 on 2026-03-29 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tecnico',
            name='esta_activo',
            field=models.BooleanField(default=True),
        ),
    ]
